# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.microservice.name }}-svc
spec:
  selector:
    app: {{ .Values.microservice.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.microservice.service.port }}
      targetPort: 8080
  type: {{ .Values.microservice.service.type }}
