{{- range .Values.microservices }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
spec:
  selector:
    app: {{ .name }}
  ports:
    - protocol: TCP
      port: {{ .service.port }}
      targetPort: 8080
  type: {{ .service.type }}
{{- end }}
