apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservice-2
spec:
  project: default
  source:
    repoURL: 'https://github.com/kkamal123/multi-microservices.git'
    targetRevision: HEAD
    path: helm
    helm:
      valueFiles:
        - values-ms2.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
